version: '3.8'

services:
  db:
    image: datascience:pg_vsdb
    environment:
      POSTGRES_DB: wiki_summarizer
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
    network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres-data: