version: '3.8'

services:
  db:
    image: datascience:pg_vsdb
    environment:
      POSTGRES_DB: wiki_summarizer
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
    network_mode: "host"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docs/backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    image: summarizer:backend
    environment:
      POSTGRES_DB_URL: ${POSTGRES_DB_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    network_mode: "host"
  frontend:
    image: summarizer:frontend
    environment:
      FASTAPI_URL: ${FASTAPI_URL}
    network_mode: "host"
volumes:
  postgres-data: